# Use Python image docker to build
image: docker:latest

before_script:
  - apt install -y python
  - python -V                                   # Print out python version for debugging
  - echo $Gitlab_Username
#  # Install Docker
#  - apt-get install curl
#  - curl -fsSL get.docker.com -o get-docker.sh
#  - sh get-docker.sh
#  - systemctl start docker

stages:
  - build
  - test
  - deploy

# Build Stage
build_docker:
  script:
    - docker login registry.gitlab.com -u $Gitlab_Username -p $Personal_Access_Token
    - docker build -t registry.gitlab.com/sappy5678/weather_calendar/Backend:Server ./Backend
    - docker push registry.gitlab.com/sappy5678/weather_calendar/Backend:Server

    - docker login -u $Gitlab_Username -p $Dockerhub
    - docker build -t sappy5678/weather_calendar:Backend_Server ./Backend
    - docker push sappy5678/weather_calendar:Backend_Server

  stage: build
#  only:
#    - master



