branch-defaults:
  default:
    environment: null
environment-defaults:
  weatherCalendar-env:
    branch: null
    repository: null
global:
  application_name: weather_calendar
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Docker running on
    64bit Amazon Linux/2.8.0
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
